### ISSUE TITLE
stop-opacity property does not support dimension values

### ISSUE THREAD

**Issue by andrew-hm** [plantuml-stdlib/gilbarbara-plantuml-sprites#1]
When I run, `./svgsFolderUrl2plantUmlSprites.groovy https://github.com/gilbarbara/logos/tree/master/logos`, I am getting a nasty error around the firefox icon:

```
java.awt.image.ImagingOpException: Unable to transform src image
	at java.awt.image.AffineTransformOp.filter(AffineTransformOp.java:285)
	at org.apache.batik.ext.awt.image.rendered.AffineRed.genRect(AffineRed.java:193)
	at org.apache.batik.ext.awt.image.rendered.AffineRed.copyData(AffineRed.java:109)
	at org.apache.batik.ext.awt.image.rendered.PadRed.copyData(PadRed.java:88)
	at org.apache.batik.ext.awt.image.rendered.PadRed.copyData(PadRed.java:88)
	at org.apache.batik.ext.awt.image.rendered.PadRed.copyData(PadRed.java:88)
	at org.apache.batik.ext.awt.image.rendered.AbstractRed.getData(AbstractRed.java:526)
	at org.apache.batik.ext.awt.image.rendered.CompositeRed.genRect(CompositeRed.java:188)
	at org.apache.batik.ext.awt.image.rendered.CompositeRed.copyData(CompositeRed.java:139)
	at org.apache.batik.ext.awt.image.rendered.PadRed.copyData(PadRed.java:88)
	at org.apache.batik.ext.awt.image.rendered.ColorMatrixRed.copyData(ColorMatrixRed.java:116)
	at org.apache.batik.ext.awt.image.rendered.Any2sRGBRed.copyData(Any2sRGBRed.java:166)
	at org.apache.batik.ext.awt.image.rendered.FormatRed.copyData(FormatRed.java:116)
	at org.apache.batik.ext.awt.image.rendered.AbstractRed.getData(AbstractRed.java:526)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(GraphicsUtil.java:264)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(GraphicsUtil.java:455)
	at org.apache.batik.ext.awt.image.renderable.PadRable8Bit.paintRable(PadRable8Bit.java:135)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(GraphicsUtil.java:440)
	at org.apache.batik.ext.awt.image.renderable.PadRable8Bit.paintRable(PadRable8Bit.java:135)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(GraphicsUtil.java:440)
	at org.apache.batik.ext.awt.image.renderable.FilterChainRable8Bit.paintRable(FilterChainRable8Bit.java:251)
	at org.apache.batik.ext.awt.image.GraphicsUtil.drawImage(GraphicsUtil.java:440)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:549)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.CanvasGraphicsNode.primitivePaint(CanvasGraphicsNode.java:159)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.CompositeGraphicsNode.primitivePaint(CompositeGraphicsNode.java:165)
	at org.apache.batik.gvt.AbstractGraphicsNode.paint(AbstractGraphicsNode.java:509)
	at org.apache.batik.gvt.renderer.MacRenderer.repaint(MacRenderer.java:361)
	at org.apache.batik.gvt.renderer.MacRenderer.repaint(MacRenderer.java:291)
	at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:111)
	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
	at org.apache.batik.transcoder.Transcoder$transcode.call(Unknown Source)
	at svgsFolderUrl2plantUmlSprites.svg2Png(svgsFolderUrl2plantUmlSprites.groovy:115)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:351)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:194)
	at svgsFolderUrl2plantUmlSprites$_run_closure2.doCall(svgsFolderUrl2plantUmlSprites.groovy:55)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:428)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3562)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3547)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collect(DefaultGroovyMethods.java:3647)
	at org.codehaus.groovy.runtime.dgm$101.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at svgsFolderUrl2plantUmlSprites.run(svgsFolderUrl2plantUmlSprites.groovy:50)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:254)
	at groovy.lang.GroovyShell.run(GroovyShell.java:360)
	at groovy.lang.GroovyShell.run(GroovyShell.java:349)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:652)
	at groovy.ui.GroovyMain.run(GroovyMain.java:398)
	at groovy.ui.GroovyMain.access$1400(GroovyMain.java:68)
	at groovy.ui.GroovyMain$GroovyCommand.process(GroovyMain.java:322)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:142)
	at groovy.ui.GroovyMain.main(GroovyMain.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:111)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:129)
org.w3c.dom.DOMException: file:/tmp/svgsFolderUrl2plantUmlSprites/firefox.svg:
The attribute "style" represents an invalid CSS declaration ("stop-color:#C42482;stop-opacity:9.000000e-02").
Original message:
The "stop-opacity" property does not support dimension values.
```

**Comment by rabelenda** [comment]
This issue is associated to [this batik transcoder issue](https://issues.apache.org/jira/browse/BATIK-1163). 

Maybe someone can fix that in batik or we can just push (mention our interest in issue report) for the issue to be fixed?

We use the batik transcoder library to convert SVG images into PNG ones, and then use plantuml library to convert them to sprites.
